### PR TITLE
Don't dump commands at the beginning of the row tag

### PR DESCRIPTION
**Pull request by fhs**
This prevents Load from adding commands that are not running to the
beginning of the row tag. Every Dump/Load cycle adds more of these
commands, further polluting the row tag.

Update #290

### CODE REVIEW

**Comment by rjkroege** [comment]
Oops. I think that the merge hasn't done the right thing with the binary representation of the font data. Can you maybe take a look?

**Comment by fhs** [comment]
I've added back the font files that got deleted accidentally, and also found one that was never checked in. The font should be ok now.

**Comment by fhs** [comment]
The issue is that `.gitattributes` on master is wrong and it's changing the line ending of `build/font/lucsans/euro.8.font` to CRLF. Nothing I do in this PR seems to help. Maybe this is best fixed by pushing the correct `.gitattributes` file (along with fixed font files) directly to master.

**Comment by fhs** [comment]
The PR test in Travis CI has CRLF ending:
```
$ git clone --depth=50 https://github.com/rjkroege/edwood.git
...
$ cd edwood/
$ git fetch origin +refs/pull/290/merge:
...
$ git checkout -qf FETCH_HEAD
$ file build/font/lucsans/euro.8.font
build/font/lucsans/euro.8.font: ASCII text, with CRLF line terminators
```
Checking it out directly doesn't have CRLF ending:
```
$ git clone --depth=50 --branch=dump-rowtag-without-commands https://github.com/fhs/edwood.git 
...
$ file edwood/build/font/lucsans/euro.8.font 
edwood/build/font/lucsans/euro.8.font: ASCII text
```

**Pull request merged**
