### PR TITLE
Refactored so that OEB has Elog and editclean

### PR DESCRIPTION
**Pull request by camsn0w**
Refactored so that OEB has Elog and editclean to separate functionality out of file for #97 #334

### CODE REVIEW

**Comment by rjkroege** [comment]
Please rebase

**Review by rjkroege — CHANGES_REQUESTED** [review]
In 57f0364d69d8a3b33f0fed388185f4e474b274c8 (HEAD -> ObserverHasElog)

* [ ] Call the `elog` module `sam`.

* [ ] `addr.go:4`: Please format your imports like this:

	```go
	import (
		"strings"

		"github.com/rjkroege/edwood/internal/elog"
	)'''

	The general pattern is imports from the Go standard library first, then
	a blank line, then the remaining imports.

* [ ] Fix the imports everywhere else. You also need to do this for the `util` package.

* There's a good discussion to be had about what else belongs in the `sam` module.
But that's a concern for the future and not germane to this CL.

* FYI: `file.go:36`: the comment you (correctly) moved  is something that you will need to
remember when writing the wrapper functions from `ObservableEditableBuffer` to `file.Buffer`
a few PRs further in the future.

* Thanks for remembering to move the tests into the `elog` package too.

**Comment by camsn0w** [comment]
> In [57f0364](https://github.com/rjkroege/edwood/commit/57f0364d69d8a3b33f0fed388185f4e474b274c8) (HEAD -> ObserverHasElog)
> 
> * [ ]  Call the `elog` module `sam`.
> * [ ]  `addr.go:4`: Please format your imports like this:
>   ```go
>    import (
>    	"strings"
>   
>    	"github.com/rjkroege/edwood/internal/elog"
>    )'''
>   
>    The general pattern is imports from the Go standard library first, then
>    a blank line, then the remaining imports.
>   ```
> * [ ]  Fix the imports everywhere else. You also need to do this for the `util` package.
> * There's a good discussion to be had about what else belongs in the `sam` module.
>   But that's a concern for the future and not germane to this CL.
> * FYI: `file.go:36`: the comment you (correctly) moved  is something that you will need to
>   remember when writing the wrapper functions from `ObservableEditableBuffer` to `file.Buffer`
>   a few PRs further in the future.
> * Thanks for remembering to move the tests into the `elog` package too.
I have another branch I'll put up in a moment for the import changes, I apoligize as I thought I put it up prior to my flight yesterday.

**Review by rjkroege — APPROVED** [review]
Review requests are satisfied in subsequent PRs so lgtm

**Pull request closed without merging**
