### PR TITLE
Test Windows build in AppVeyor

### PR DESCRIPTION
**Pull request by fhs**
AppVeyor will need permission to this repo.
Sample build: https://ci.appveyor.com/project/fhs/edwood

I'm skipping all the tests that are failing for now.

Helps #116

### CODE REVIEW

**Comment by rjkroege** [comment]
Do we need Appveyor and Travis? Can Travis do windows? I'd prefer to only have one continuous build solution.

**Comment by rjkroege** [comment]
And if we need AppVeyor for windows, should we abandon Travis? I don't have any particular objection to the code changes but I'd like to have us end up with only end continuous builder. 😊

**Comment by fhs** [comment]
Travis CI windows support was just introduces in [Oct 2018](https://blog.travis-ci.com/2018-10-11-windows-early-release), so it's very new and kind of in "beta". We could give that a try.

AppVeyor doesn't support macOS and Travis CI does. I'd like to run tests on macOS at some point, so if we're going to stick with one, I think it should be Travis CI.

**Comment by fhs** [comment]
Opened #201 with Travis config changes. Closing this one.

**Pull request closed without merging**
