### PR TITLE
Undo pieces have nr

### PR DESCRIPTION
**Pull request by camsn0w**
Each piece now records it's Nr (either found or given with insert) to identify if the given piece has non-ascii characters or not. Dependent on #368

### CODE REVIEW

**Review by rjkroege — CHANGES_REQUESTED** [review]
# Context

I'm assuming in the following that you will *add* new forwarding functions in `file.ObservableEditableBuffer`
that use `file.Buffer`. I'm going to call these the *new* forwarding functions.

Per email earlier: I suggest that these functions should live side-by-side with the existing
functions. And (best!) a runtime flag can switch between the new and old functions. This way: all
of the code can co-exist and we can try out the Edwood with the new backing buffer.

# Comments

* file/undo.go:1 we should rename `undo.go` to `buffer.go` at some point. Not
in this PR.

* file/undo.go:106 You shouldn't need to add `mod` or `treatasclean` here.
New `oeb.SaveableAndDirty` can be implemented in terms of `Buffer.Dirty()`. Note that means that 
file/undo.go:576 can be removed. 

* General observation: try to keep `file.Buffer`'s semantics as unchanged as possible. The forwarding
functions should adapt `file.Buffer` to OEB's semantic guarantees outside the `file` package.

* file/undo.go:110 Hm. I'm not sure about this.

* file/undo.go:137 Move the test only code into the `_test.go` file.

* file/undo.go:143 Document the nr argument here and elsewhere.

* file/undo.go:171 `off` is a byte index. So: we would have
had to (perhaps implicitly) compute `beforeNr` before calling `Buffer.Insert`. So you can update the split
pieces's rune count without using `utf8.RuneCount`. At a minimum: you should only count the
rune contents of the smaller slice.

* file/undo.go:187 Test only? If so, move to `undo_test.go`

* file/undo.go:251 Same issue applies as with `Insert`. Having computed
`off` and `length`, we'll already have computed `nr` implicitly. 

* General comment: it's essential to note which arguments index in runes while which index in
bytes.

* `nr` is an `int` but all the original `file.Buffer` position types are `int64`. This is a nasty bug waiting
to happen on 32bit systems. Rune counts and indicies need also to be `int64`

* Idea: wrap the `file.Buffer` with rune-oriented implementation. Introduce a new type for all positional
and length arguments. Something ike this:

```go
type OffsetTuple struct {
	b int64
	r int64
}
```

and use them in `file.Buffer`

* Add the interface-satisfying construct for `file.Buffer`: it currently satisfies `io.ReaderAt`.

* In a different PR: make `file.Buffer` also implement `io.RuneReader`
and remove `ReadC`. (And RuneReaderReverse and Seeker) and some more.
Etc.

* file/undo.go:341 Please explain how `ChangeInfo` is meant to be used.
I don't understand how you can use construct the correct observer calls in OEB from the contents of
a `ChangeInfo`.

* file/undo.go:532 `delete` mutates the piece backing and so must update
the `nr` value.

* file/undo.go:541 why? You can implement this externally in OEB?

* file/undo.go:550 Why? The cachedPiece should be an internal
detail of `file.Buffer`. Also: no concept of commit needs to exist. Let `file.Buffer` handle this.

* Most of these functions from 550 down seem unnecessary. We can discuss further.

* The `file.Buffer` action will probably need to track `seq` yes?

* file/undo.go:182 The diff would have been smaller if you'd *added* new
functions for making a buffer with a `nr` value. No code yet uses these entry points so they can (and
should perhaps) have new names.

* file/undo_test.go:11 Needs additional cases where there are non-ASCII
runes at all the boundary points.

**Comment by camsn0w** [comment]
file/undo.go:1 we should rename undo.go to buffer.go at some point. Not
in this PR.
 
    Sounds good
file/undo.go:106 You shouldn't need to add mod or treatasclean here.
New oeb.SaveableAndDirty can be implemented in terms of Buffer.Dirty(). Note that means that
file/undo.go:576 can be removed.
 
    Ok
General observation: try to keep file.Buffer's semantics as unchanged as possible. The forwarding
functions should adapt file.Buffer to OEB's semantic guarantees outside the file package.
 
	Ok
file/undo.go:110 Hm. I'm not sure about this.
 
	Will delete it now that I know it doesn’t work.
file/undo.go:137 Move the test only code into the _test.go file.
 
	Will do
file/undo.go:143 Document the nr argument here and elsewhere.
 
	Will do
file/undo.go:171 off is a byte index. So: we would have
had to (perhaps implicitly) compute beforeNr before calling Buffer.Insert. So you can update the split
pieces's rune count without using utf8.RuneCount. At a minimum: you should only count the
rune contents of the smaller slice.
 
	Makes sense
file/undo.go:187 Test only? If so, move to undo_test.go
I anticipate it will be used elsewhere eventually, right now it’s just for tests though
file/undo.go:251 Same issue applies as with Insert. Having computed
off and length, we'll already have computed nr implicitly.
 
    Makes sense
General comment: it's essential to note which arguments index in runes while which index in
Bytes.
 
    I wholeheartedly agree, the ambiguity gets confusing 
nr is an int but all the original file.Buffer position types are int64. This is a nasty bug waiting to happen on 32bit systems. Rune counts and indicies need also to be int64
 
    Sounds good
Idea: wrap the file.Buffer with rune-oriented implementation. Introduce a new type for all positional
and length arguments. Something ike this:
 
    I like the idea, Sounds good
type OffsetTuple struct {
	b int64
	r int64
}
and use them in file.Buffer
Add the interface-satisfying construct for file.Buffer: it currently satisfies io.ReaderAt.
 
    Which interface-satisfying construct? OffsetTuple?
In a different PR: make file.Buffer also implement io.RuneReader
and remove ReadC. (And RuneReaderReverse and Seeker) and some more.

Etc.
    Ok
file/undo.go:341 Please explain how ChangeInfo is meant to be used.
I don't understand how you can use construct the correct observer calls in OEB from the contents of
a ChangeInfo.
 
    Following more tests I discovered it doesn’t work, thanks for pointing this out
file/undo.go:532 delete mutates the piece backing and so must update
the nr value.
 
    Thanks for catching that, that may be why my implementation doesn’t work
file/undo.go:541 why? You can implement this externally in OEB?
 
	It was useful for both undo_test and OEB as well as implementing various interfaces.
file/undo.go:550 Why? The cachedPiece should be an internal
detail of file.Buffer. Also: no concept of commit needs to exist. Let file.Buffer handle this.
 
    text_test.go needs a GetCache
Most of these functions from 550 down seem unnecessary. We can discuss further.
 
    They were put there to either maintain compatibility with tests or to help keep track of indexes between bytes and runes (poorly as I’ve recently discovered)
The file.Buffer action will probably need to track seq yes?
 
    I thought we are getting rid of seq?
file/undo.go:182 The diff would have been smaller if you'd added new
functions for making a buffer with a nr value. No code yet uses these entry points so they can (and
should perhaps) have new names.
 
    My bad, I’m remembering you mentioned both
file/undo_test.go:11 Needs additional cases where there are non-ASCII
runes at all the boundary points.
 
	I partially wrote the tests and discovered some issues at these edge cases, I will remove the extra junk from this PR and them up.

**Review by rjkroege — CHANGES_REQUESTED** [review]
# Previous Discussion
Continuing from comments on 6044fb2

> 
> > * file/undo.go:187 Test only? If so, move to `undo_test.go`
> 
> I anticipate it will be used elsewhere eventually, right now it’s just for tests though

I think the tests need to be updated to use the modified entry points that take `OffsetTuple`
objects?


> > * General comment: it's essential to note which arguments index in runes while which index in
> > bytes.
> 
> I wholeheartedly agree, the ambiguity gets confusing

Idea. It's possible to create new types:

```
type RuneOff int
type ByteOff int
```

And the compiler will enforce not assigning them to each other. So `OffsetTuple` becomes:

```go
type OffsetTuple struct {
	b ByteOff
	r RuneOff
}
```

I have convinced myself while re-reading the code that the types here should be `int`. But note
that some of the functions needed to satisfy interfaces like `io.ReaderAt` have to take `int64` types
for compatability. I have not reviewed the code carefully with regards to this issue. We can
iterate towards that.

> > * Add the interface-satisfying construct for `file.Buffer`: it currently satisfies `io.ReaderAt`.
> 
> Which interface-satisfying construct? OffsetTuple?

No. Like this fragment from text.go:47

```go
	_ file.BufferObserver = (*Text)(nil) // Enforce at compile time that Text implements BufferObserver
```

Something like:

```go
var (
	_ io.ReaderAt = (*file.Buffer)(nil)
)
```

>
> > * file/undo.go:541 why? You can implement this externally in OEB?
> 
> It was useful for both undo_test and OEB as well as implementing various interfaces.

Where? It's never called?

> > * file/undo.go:550 Why? The cachedPiece should be an internal
> > detail of `file.Buffer`. Also: no concept of commit needs to exist. Let `file.Buffer` handle this.
> 
> text_test.go needs a GetCache

The cache concept should be an internal detail of `file.File` and (implemented differently) `file.Buffer`. I'll update the test to obviate.

> > 
> > * The `file.Buffer` action will probably need to track `seq` yes?
> 
> I thought we are getting rid of seq?
>

We continue to need a scheme to globalize undo/redo across
`file.ObservableEditableBuffer` instances. I've (reluctantly)
convinced myself that some `seq` support remains necessary.

# New Comments
From ef7923b360c1eaea3edf4239d9635880138e17ef

General observation: I'd prefer that you rebase your PRs. You have my change
#367 inline in your change. This makes it extremely messy to review. I removed
this from your PR. You should do that and then rebase on master.

* dumpfile/legacy_parse_test.go:264 This change in the
comment is wrong. Remember that OEB is an example of a facade design pattern:
it provides a stable interface to complicated stuff underneath. Your changes are *underneath*.
They should *not* be visible outside of the `file` module. Later, we can provide new entry
points in OEB for portions of Edwood that are byte/rune coordinate difference aware. But
that comes *later*.

* file/file.go:62 Here and in several other places, you
have changed `Insert` to `InsertWithNr`. Some of these changes are wrong. Please
review and correct.

* file/undo.go:174 Per discussion about `OffsetTuple`: are you
still planning on doing that?

* file/undo.go:143 I'm mildly unhappy with the name `InsertWithNr` but don't have any better ideas. This name accurately captures what the function does. I might propose changing it later. 🙂 (Non-actionable comment.)

* file/undo.go:467 `Nr` should be returning an int. `nr` is an int.
`utf8.RuneCount` returns an int.

* file/undo_test.go:309 maybe `mandarinBytes`. Maybe check the spelling? And: 

* file/undo_test.go:314 as you refine the implementation to remove the
calls to `utf8.RuneCount` inside of `file.Buffer`, you need to replace these calls with the rune-aware
functions.

* file/undo.go:188 Perhaps replace the call to `utf8.RuneCount` with
`len(data)`. This preserves the pre-existing ASCII-only semantics for the tests but would force
tests like `TestPieceNr` to fail if they don't use the rune-aware entry points.

* frame/insert.go:135 Your CL should not have modified this code right?
Please scope your search and replace ops more judiciously. I recommend `gofmt -r` for renmaing
functions. Please revert all the unnecessary replaces.

**Comment by rjkroege** [comment]
I landed this with some changes per email discussion. Thanks so much for the work.

**Pull request closed without merging**
