### PR TITLE
Drop support for Go 1.10

### PR DESCRIPTION
**Pull request by fhs**
Go 1.10 is more than 1 year old now and it's no longer supported upstream.
Go's [release policy](https://golang.org/doc/devel/release.html#policy) is to support last two major releases with critical bug fixes.

This will also give us quicker results from Travis CI.

### CODE REVIEW

**Comment by rjkroege** [comment]
Can you take a look at what's going on here with the build and share your thoughts? This seems odd to me. I thought that Mac in Travis was on the `duitdraw` path? Why would this change alter that behaviour?

**Comment by fhs** [comment]
duitdraw is currently not being tested in any of the systems except Windows. On macOS, it uses `devdraw` from plan9port installed via homebrew, and it looks like homebrew is failing for some reason.

**Comment by fhs** [comment]
It looks like plan9port was [removed from homebrew](https://github.com/Homebrew/homebrew-core/pull/38394). I think we should build it manually and [cache](https://docs.travis-ci.com/user/caching/) the directory where plan9port is installed.

**Comment by fhs** [comment]
Or we can do what we're doing for Linux: add macOS binaries for `devdraw` and `9pserver` to git repo.

**Comment by rjkroege** [comment]
I'll do that.

**Pull request merged**
